import { useEffect, useState } from 'react'
import { RECOVERY_CHANGED_EVENT, dismissRevokedFarmRecovery, readRevokedFarmRecovery } from '../data/revokedFarmRecovery'
import { supabaseConfig } from '../lib/supabaseConfig'

export function RevokedFarmRecovery({ userId }: { userId: string | null }) {
  const [version, setVersion] = useState(0); const [confirming, setConfirming] = useState<string | null>(null); const [error, setError] = useState('')
  // A record added while this view is mounted (a tied Grain settings draft found when a screen loaded) shows without a navigation.
  useEffect(() => { const bump = () => setVersion((value) => value + 1); window.addEventListener(RECOVERY_CHANGED_EVENT, bump); return () => window.removeEventListener(RECOVERY_CHANGED_EVENT, bump) }, [])
  if (!userId || typeof window === 'undefined') return null
  let records
  try { records = readRevokedFarmRecovery(window.localStorage, supabaseConfig.projectRef, userId) } catch (caught) { return <section className="revoked-work-recovery" role="alert"><h2>Saved work needs attention</h2><p>{caught instanceof Error ? caught.message : 'Farm Rx could not safely read saved recovery work on this device.'}</p></section> }
  if (!records.length) return null
  const exportRecord = (id: string) => { const record = records.find((item) => item.id === id); if (!record) return; const url = URL.createObjectURL(new Blob([JSON.stringify(record, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `farm-rx-recovery-${record.farmId}-${record.capturedAt.slice(0, 10)}.json`; document.body.append(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 0) }
  return <section className="revoked-work-recovery" aria-label="Saved work that needs your review" data-version={version}><h2>Saved work needs your review</h2>{records.some((record) => record.reason === 'farm_access_removed') && <p>Your access to a farm changed. Farm Rx kept these unsent changes on this device, but will never send them automatically—even if access is restored later.</p>}{records.some((record) => record.reason === 'simultaneous_edit') && <p>Two tabs of this browser changed the same Grain setting at the same moment. The change kept on screen was saved; the other is kept here for you to check, and is never sent by itself.</p>}{error && <p role="alert">{error}</p>}{records.map((record) => <article key={record.id}><div><strong>{record.kind === 'scouting_cleanup' ? 'Scouting cleanup' : record.kind === 'needs_attention' ? 'Save needing attention' : record.kind === 'settings_drafts' ? 'Unsaved Grain settings' : record.kind === 'university_defaults' ? 'Budget line seeded from the U of I defaults' : 'Unsent saved change'}</strong><span>{record.reason === 'simultaneous_edit' ? 'Edited in two tabs at once' : 'Farm access removed'} {new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(record.capturedAt))}</span></div><div><button type="button" className="secondary-action" onClick={() => exportRecord(record.id)}>Export copy</button>{confirming === record.id ? <><button type="button" className="danger-action" onClick={() => { try { dismissRevokedFarmRecovery(window.localStorage, supabaseConfig.projectRef, userId, record.id); setConfirming(null); setError(''); setVersion((value) => value + 1) } catch (caught) { setError(caught instanceof Error ? caught.message : 'This saved work could not be dismissed.') } }}>Yes, dismiss</button><button type="button" onClick={() => setConfirming(null)}>Keep it</button></> : <button type="button" onClick={() => setConfirming(record.id)}>Dismiss</button>}</div></article>)}</section>
}
