$ErrorActionPreference='Stop';. (Join-Path $PSScriptRoot 'maple-synthetic-docker-topology-plan.ps1')
function A($v,$m){if(-not$v){throw $m}}
$id=[guid]'11111111-2222-4333-8444-555555555555';$plan=New-MapleSyntheticDockerTopologyPlan $id 62131 62132;A(Assert-MapleSyntheticDockerTopologyPlan $plan)'plan refused';A($plan.Kind-ceq'planning-topology-sketch'-and-not$plan.Executable)'not honest topology plan';A(-not$plan.PortPreflight.Implemented-and$plan.PortPreflight.KnownRace-match'cannot reserve')'port race not explicit';A(-not$plan.FixtureLineage.Resolved-and$plan.FixtureLineage.ExecutionTimeLocalInspectRequired-and-not$plan.FixtureLineage.ObservedLocalPresenceClaimed-and$plan.FixtureLineage.Reason-match'execution-time local inspect')'fixture lineage overclaimed';A(($plan.LoopbackPublishes-join'|')-ceq'127.0.0.1:62131:5432|127.0.0.1:62132:3000')'publish topology not loopback'
A($plan.Images.SupabasePostgres.Ref-ceq'public.ecr.aws/supabase/postgres@sha256:9faa7279bcf1fd6834e65dc876b11e39cb53030bcb3d653beb7e5668200acbb5')'postgres digest drift';A($plan.Images.Postgrest.ExpectedLocalImageId-ceq'sha256:488093de819567422bc1d37cb79da6e84bca3726bac321daeed618f0ed957888')'postgrest id drift';A($plan.Images.FaketimeBuilder.Ref-ceq'debian@sha256:7b140f374b289a7c2befc338f42ebe6441b7ea838a042bbd5acbfca6ec875818')'builder digest drift';A(-not$plan.Images.MutableTagsAllowed-and-not$plan.Images.SupabasePostgres.PullAllowed)'mutable/pull policy weakened'
A(($plan.InitializationSchemaContract.Roles|Where-Object Name -ceq 'anon').Login-eq$false)'anon must be NOLOGIN';A(($plan.InitializationSchemaContract.Roles|Where-Object Name -ceq 'authenticated').Login-eq$false)'authenticated must be NOLOGIN';$auth=$plan.InitializationSchemaContract.Roles|Where-Object Name -ceq 'authenticator';A($auth.Login-and-not$auth.SecretValueIncluded-and$auth.SecretSource-ceq'private execution input only')'authenticator secret contract invalid';A($plan.InitializationSchemaContract.ProofRelation-ceq'api.fixture_proof'-and$plan.InitializationSchemaContract.ExactSyntheticRow.contract_hash-ceq'maple-synthetic-11111111222243338444555555555555'-and$plan.InitializationSchemaContract.ExactSyntheticRow.result-ceq'fixture-ready')'proof row drift';A(($plan.InitializationSchemaContract.Grants-join'|')-match'grant select on api.fixture_proof'-and($plan.InitializationSchemaContract.Revokes-join'|')-match'revoke all on api.fixture_proof from public')'grant/revoke contract incomplete'
A(($plan.PostgrestConfigurationContract.EnvironmentKeyNames-join'|')-ceq'PGRST_DB_URI|PGRST_DB_SCHEMAS|PGRST_DB_ANON_ROLE|PGRST_SERVER_PORT|PGRST_JWT_SECRET')'PostgREST env keys drift';A($plan.PostgrestConfigurationContract.ApplicationName-ceq'postgrest-synthetic-11111111222243338444555555555555'-and-not$plan.PostgrestConfigurationContract.SecretValuesIncluded-and-not$plan.PostgrestConfigurationContract.JwtValuesIncluded)'PostgREST evidence leaks values';A(-not$plan.FrozenBuildOfflineProof.Resolved-and$plan.FrozenBuildOfflineProof.RequiredCommand-match'--network=none'-and$plan.FrozenBuildOfflineProof.Risk-match'cache')'offline build proof overclaimed'
$mutations=@(
  @{Name='roles cleared';Apply={param($p)$p.InitializationSchemaContract.Roles=@()}},
  @{Name='role changed';Apply={param($p)$p.InitializationSchemaContract.Roles[0].Login=$true}},
  @{Name='columns cleared';Apply={param($p)$p.InitializationSchemaContract.Columns=@()}},
  @{Name='column changed';Apply={param($p)$p.InitializationSchemaContract.Columns[0].Type='uuid'}},
  @{Name='row changed';Apply={param($p)$p.InitializationSchemaContract.ExactSyntheticRow.result='wrong'}},
  @{Name='grants changed';Apply={param($p)$p.InitializationSchemaContract.Grants=@('grant all')}},
  @{Name='revokes changed';Apply={param($p)$p.InitializationSchemaContract.Revokes=@()}},
  @{Name='app name changed';Apply={param($p)$p.PostgrestConfigurationContract.ApplicationName='wrong'}},
  @{Name='env keys changed';Apply={param($p)$p.PostgrestConfigurationContract.EnvironmentKeyNames=@('PGRST_DB_URI')}},
  @{Name='secret boolean changed';Apply={param($p)$p.PostgrestConfigurationContract.SecretValuesIncluded=$true}},
  @{Name='executable deleted';Apply={param($p)$p.PSObject.Properties.Remove('Executable')}},
  @{Name='port preflight deleted';Apply={param($p)$p.PortPreflight.PSObject.Properties.Remove('Implemented')}},
  @{Name='offline proof deleted';Apply={param($p)$p.FrozenBuildOfflineProof.PSObject.Properties.Remove('Resolved')}},
  @{Name='image true flag changed type';Apply={param($p)$p.Images.SupabasePostgres.RequireLocalIdEqualsDigest='true'}},
  @{Name='image digest changed';Apply={param($p)$hash='1'*64;$p.Images.SupabasePostgres.Ref="public.ecr.aws/supabase/postgres@sha256:$hash";$p.Images.SupabasePostgres.ExpectedLocalImageId="sha256:$hash"}},
  @{Name='lineage resolved';Apply={param($p)$p.FixtureLineage.Resolved=$true}},
  @{Name='lineage reason changed';Apply={param($p)$p.FixtureLineage.Reason='changed'}}
)
foreach($field in @('MutableTagsAllowed')){$mutations+=@{Name="deleted Images.$field";Apply={param($p)$p.Images.PSObject.Properties.Remove($field)}.GetNewClosure()}}
foreach($imageName in @('SupabasePostgres','Postgrest','FaketimeBuilder')){$mutations+=@{Name="deleted $imageName.PullAllowed";Apply={param($p)$p.Images.$imageName.PSObject.Properties.Remove('PullAllowed')}.GetNewClosure()}}
foreach($spec in @(@('InitializationSchemaContract','ContainsSecrets'),@('PostgrestConfigurationContract','SecretValuesIncluded'),@('PostgrestConfigurationContract','JwtValuesIncluded'),@('PostgrestConfigurationContract','EvidenceMayContainValues'))){$owner=$spec[0];$field=$spec[1];$mutations+=@{Name="deleted $owner.$field";Apply={param($p)$p.$owner.PSObject.Properties.Remove($field)}.GetNewClosure()}}
foreach($field in @('Resolved','SelectedExpectedImmutableLineage','ExecutionTimeLocalInspectRequired','ObservedLocalPresenceClaimed','Reason')){$mutations+=@{Name="deleted FixtureLineage.$field";Apply={param($p)$p.FixtureLineage.PSObject.Properties.Remove($field)}.GetNewClosure()}}
foreach($mutation in $mutations){$bad=($plan|ConvertTo-Json -Depth 12|ConvertFrom-Json);& $mutation.Apply $bad;$refused=$false;try{Assert-MapleSyntheticDockerTopologyPlan $bad|Out-Null}catch{$refused=$true};A($refused)("mutation accepted: "+$mutation.Name)}
foreach($resource in $plan.Resources){$index=[array]::IndexOf([object[]]$plan.Cleanup,($plan.Cleanup|Where-Object{$_.Action-eq'inspect'-and$_.Name-ceq$resource.Name}|Select-Object -First 1));A($index-ge0)'ownership inspect missing';$later=@($plan.Cleanup|Select-Object -Skip($index+1)|Where-Object{$_.Name-ceq$resource.Name});A($later.Count-ge1-and@($later|Where-Object{-not$_.OnlyAfterExactInspection}).Count-eq0)'cleanup not ownership gated'}
$source=Get-Content -Raw (Join-Path $PSScriptRoot 'maple-synthetic-docker-topology-plan.ps1');A($source-match'non-executing planning/topology sketch'-and-not($source-match'ProcessStartInfo|Invoke-MapleSwapStateMachine'))'execution claim remains';$planJson=$plan|ConvertTo-Json -Depth 12;A(-not($planJson-match'PGRST_JWT_SECRET\s*=|postgres(?:ql)?://[^"\s]*:[^@"\s]*@')-and-not($source-match'docker\s+pull'))'credential value or pull behavior present'
Write-Output 'MAPLE_SYNTHETIC_DOCKER_TOPOLOGY_PLAN_REGRESSION_PASS'
