param([guid]$SyntheticId=[guid]::NewGuid(),[int]$DbPort=62141,[switch]$Execute,[switch]$UnsafeReviewed)
$ErrorActionPreference='Stop';$script:MapleDbFixtureExecutionUnlocked=$false

function Protect-MapleDbFixtureText([string]$Text,[string[]]$SensitiveValues){$safe=[string]$Text;foreach($value in @($SensitiveValues)){if(-not[string]::IsNullOrEmpty($value)){$safe=$safe.Replace($value,'[REDACTED]')}};$safe}
function Invoke-MapleDbFixtureProcess {
  param([string[]]$Argv,[string]$PrivateStdin,[hashtable]$PrivateEnvironment=@{},[string[]]$PrivateSensitiveValues=@())
  $psi=[Diagnostics.ProcessStartInfo]::new('docker');$psi.UseShellExecute=$false;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.RedirectStandardInput=$true
  foreach($argument in $Argv){$null=$psi.ArgumentList.Add($argument)};foreach($name in $PrivateEnvironment.Keys){$psi.Environment[$name]=[string]$PrivateEnvironment[$name]}
  $process=[Diagnostics.Process]::Start($psi);$stdoutTask=$process.StandardOutput.ReadToEndAsync();$stderrTask=$process.StandardError.ReadToEndAsync()
  if($null-ne$PrivateStdin){$process.StandardInput.Write($PrivateStdin)};$process.StandardInput.Close();$process.WaitForExit();[Threading.Tasks.Task]::WaitAll(@($stdoutTask,$stderrTask))
  [pscustomobject]@{ExitCode=$process.ExitCode;Stdout=(Protect-MapleDbFixtureText $stdoutTask.Result $PrivateSensitiveValues);Stderr=(Protect-MapleDbFixtureText $stderrTask.Result $PrivateSensitiveValues)}
}
function New-MaplePrivateDockerEnvFile([string]$Name,[string]$Value,[scriptblock]$PostCreateProbe=$null,[scriptblock]$PreWriteProbe=$null){
  if($Name-cnotin@('POSTGRES_PASSWORD','PGOPTIONS')-or[string]::IsNullOrEmpty($Value)){throw 'MAPLE_DBFIXTURE_REFUSED: private env-file input invalid.'}
  $path=Join-Path ([IO.Path]::GetTempPath()) ('maple-dbfixture-'+[guid]::NewGuid().ToString('N')+'.env');$success=$false
  try{
    $expected="$Name=$Value`n";$bytes=[Text.UTF8Encoding]::new($false).GetBytes($expected)
    $security=[Security.AccessControl.FileSecurity]::new();$user=[Security.Principal.WindowsIdentity]::GetCurrent().User;$security.SetOwner($user);$security.SetAccessRuleProtection($true,$false);$security.AddAccessRule([Security.AccessControl.FileSystemAccessRule]::new($user,'FullControl','Allow'))
    $stream=[IO.FileStream]::new($path,[IO.FileMode]::CreateNew,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None,4096,[IO.FileOptions]::WriteThrough)
    try{
      Set-Acl -LiteralPath $path -AclObject $security
      $appliedAcl=Get-Acl -LiteralPath $path;$appliedRules=@($appliedAcl.GetAccessRules($true,$true,[Security.Principal.SecurityIdentifier]))
      if(-not$appliedAcl.AreAccessRulesProtected-or$appliedAcl.GetOwner([Security.Principal.SecurityIdentifier]).Value-cne$user.Value-or$appliedRules.Count-ne1-or$appliedRules[0].IdentityReference.Value-cne$user.Value-or$appliedRules[0].AccessControlType-ne[Security.AccessControl.AccessControlType]::Allow-or($appliedRules[0].FileSystemRights-band[Security.AccessControl.FileSystemRights]::FullControl)-ne[Security.AccessControl.FileSystemRights]::FullControl){throw 'MAPLE_DBFIXTURE_REFUSED: private env-file ACL verification failed.'}
      if($null-ne$PreWriteProbe-and(&$PreWriteProbe $path)-ne$true){throw 'MAPLE_DBFIXTURE_REFUSED: private env-file pre-write exclusivity probe failed.'}
      $stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)
    }finally{if($null-ne$stream){$stream.Dispose()}}
    $readback=[IO.File]::ReadAllText($path);if($readback-cne$expected){throw 'MAPLE_DBFIXTURE_REFUSED: private env-file readback failed.'}
    if($null-ne$PostCreateProbe-and(&$PostCreateProbe $path)-ne$true){throw 'MAPLE_DBFIXTURE_REFUSED: private env-file post-create probe failed.'}
    $success=$true
    [pscustomobject]@{Path=$path;Verified=$true;Delete={if([IO.File]::Exists($path)){[IO.File]::Delete($path)}}.GetNewClosure()}
  }finally{if(-not$success-and[IO.File]::Exists($path)){[IO.File]::Delete($path)}}
}
function Test-MapleLoopbackPortAvailable([int]$Port){$listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,$Port);try{$listener.Start();$true}catch{$false}finally{$listener.Stop()}}
function New-MapleSyntheticDbFixturePlan([guid]$Id,[int]$Port){
  if($Id-eq[guid]::Empty-or$Port-lt49152-or$Port-gt65535){throw 'MAPLE_DBFIXTURE_REFUSED: id/port contract invalid.'};$token=$Id.ToString('N');$prefix="maple-synthetic-dbfixture-$token"
  [pscustomobject]@{Kind='locked-db-only-synthetic-fixture';Executable=$false;Prefix=$prefix;Token=$token;Port=$Port;Container="$prefix-db";Network="$prefix-network";Volume="$prefix-volume";OwnershipLabel="farmrx.synthetic-dbfixture=$token";ImageRef='public.ecr.aws/supabase/postgres@sha256:9faa7279bcf1fd6834e65dc876b11e39cb53030bcb3d653beb7e5668200acbb5';ImageId='sha256:9faa7279bcf1fd6834e65dc876b11e39cb53030bcb3d653beb7e5668200acbb5';ContainsSecrets=$false;EphemeralPrivateInputs='synthetic password exists only in ownership-restricted env files; SQL stdin contains only current_setting lookup and neither secrets nor file contents are serialized as plan or evidence';HealthDeadlineSeconds=90;HealthPollMilliseconds=1000;PortRace='Loopback bind is released immediately before create; a release race remains.'}
}
function Invoke-MapleDbFixtureInitialization([string]$ContainerId,[string]$Prefix,[string]$PrivateExecEnvFilePath,[scriptblock]$CheckedInvoke){
 $sql="begin; do `$do`$ begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin; end if; if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin; end if; if not exists(select 1 from pg_roles where rolname='authenticator') then create role authenticator login; end if; end `$do`$; alter role anon nologin; alter role authenticated nologin; alter role authenticator login; do `$password_rotation`$ begin execute format('alter role authenticator password %L',current_setting('farmrx.private_password')); end `$password_rotation`$; create schema if not exists api; revoke all on schema api from public; create table if not exists api.fixture_proof(contract_hash text primary key not null,result text not null); revoke all on api.fixture_proof from public; grant anon to authenticator; grant authenticated to authenticator; grant usage on schema api to anon, authenticated; grant select on api.fixture_proof to anon, authenticated; insert into api.fixture_proof(contract_hash,result) values('$Prefix','fixture-ready') on conflict(contract_hash) do update set result=excluded.result; commit;"
 & $CheckedInvoke @('exec','--env-file',$PrivateExecEnvFilePath,'-i',$ContainerId,'psql','-X','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres','-f','-') 'fixture initialize' $sql|Out-Null
}
function Invoke-MapleSyntheticDbFixtureSmoke {
 param([guid]$Id,[int]$Port,[scriptblock]$Invoke,[scriptblock]$TcpProbe,[scriptblock]$Clock,[scriptblock]$Wait,[scriptblock]$PrivateEnvFileFactory,[switch]$InternalReviewedGate)
 $plan=New-MapleSyntheticDbFixturePlan $Id $Port;if(-not$InternalReviewedGate-or@($Invoke,$TcpProbe,$Clock,$Wait,$PrivateEnvFileFactory)-contains$null){throw 'MAPLE_DBFIXTURE_REFUSED: reviewed injected boundaries required.'}
 $password='maple-'+[guid]::NewGuid().ToString('N');$recorded=@{container=$null;volume=$null;network=$null};$primary=$null;$cleanupErrors=[Collections.Generic.List[Exception]]::new();$envFile=$null;$execEnvFile=$null;$result=$null
 $redact={param([string]$Text);([string]$Text).Replace($password,'[REDACTED]')}.GetNewClosure()
 $call={param([string[]]$Argv,[string]$Operation,[string]$PrivateStdin=$null,[hashtable]$PrivateEnvironment=@{});$r=&$Invoke $Argv $PrivateStdin $PrivateEnvironment @($password);if($null-eq$r-or$null-eq$r.PSObject.Properties['ExitCode']-or$null-eq$r.PSObject.Properties['Stdout']-or$null-eq$r.PSObject.Properties['Stderr']){throw "MAPLE_DBFIXTURE_FAILED: malformed $Operation result."};[pscustomobject]@{ExitCode=$r.ExitCode;Stdout=(&$redact $r.Stdout);Stderr=(&$redact $r.Stderr)}}.GetNewClosure()
 $checked={param([string[]]$Argv,[string]$Operation,[string]$PrivateStdin=$null,[hashtable]$PrivateEnvironment=@{});$r=&$call $Argv $Operation $PrivateStdin $PrivateEnvironment;if($r.ExitCode-ne0){throw "MAPLE_DBFIXTURE_FAILED: $Operation failed."};$r}.GetNewClosure()
 $inspect={param([string]$Kind,[string]$Name);$r=&$call @($Kind,'inspect',$Name,'--format','{{json .}}') "$Kind inspect";if($r.ExitCode-eq0){try{return $r.Stdout|ConvertFrom-Json -ErrorAction Stop}catch{throw "MAPLE_DBFIXTURE_REFUSED: malformed $Kind inspection."}};$absent=@("Error: No such $Kind`: $Name","Error response from daemon: No such $Kind`: $Name","Error: No such object: $Name","Error response from daemon: No such object: $Name");if($Kind-ceq'volume'){$absent+="Error response from daemon: get $Name`: no such volume"};if($Kind-ceq'network'){$absent+="Error response from daemon: network $Name not found"};if($r.ExitCode-eq1-and$r.Stderr.Trim()-cin$absent){return $null};throw "MAPLE_DBFIXTURE_FAILED: $Kind inspection failed."}.GetNewClosure()
 $identity={param([string]$Kind,$Actual);if($Kind-ceq'container'){[string]$Actual.Id}elseif($Kind-ceq'volume'){[string]$Actual.Name}else{[string]$Actual.Id}}.GetNewClosure()
 $owner={param([string]$Kind,$Actual);if($Kind-ceq'container'){[string]$Actual.Config.Labels.'farmrx.synthetic-dbfixture'}else{[string]$Actual.Labels.'farmrx.synthetic-dbfixture'}}.GetNewClosure()
 $adopt={param([string]$Kind,[string]$Name);$actual=&$inspect $Kind $Name;if($null-eq$actual){return $null};$rid=&$identity $Kind $actual;if([string]::IsNullOrWhiteSpace($rid)-or(&$owner $Kind $actual)-cne$plan.Token){throw "MAPLE_DBFIXTURE_REFUSED: $Kind identity/ownership ambiguous."};if($null-ne$recorded[$Kind]-and$recorded[$Kind]-cne$rid){throw "MAPLE_DBFIXTURE_REFUSED: $Kind identity replaced after recording."};$recorded[$Kind]=$rid;$actual}.GetNewClosure()
 try{
  try{
   foreach($r in @(@('container',$plan.Container),@('volume',$plan.Volume),@('network',$plan.Network))){if($null-ne(&$inspect $r[0] $r[1])){throw "MAPLE_DBFIXTURE_REFUSED: pre-existing $($r[0]) collision."}}
   $image=&$checked @('image','inspect',$plan.ImageRef,'--format','{{json .}}') 'image inspect';try{$io=$image.Stdout|ConvertFrom-Json -ErrorAction Stop}catch{throw 'MAPLE_DBFIXTURE_REFUSED: malformed image inspection.'};if($io.Id-cne$plan.ImageId){throw 'MAPLE_DBFIXTURE_REFUSED: image ID mismatch.'};if((&$TcpProbe $Port)-ne$true){throw 'MAPLE_DBFIXTURE_REFUSED: loopback port occupied.'}
   foreach($r in @(@('network',$plan.Network),@('volume',$plan.Volume))){try{&$checked @($r[0],'create','--label',$plan.OwnershipLabel,$r[1]) "$($r[0]) create"|Out-Null}catch{&$adopt $r[0] $r[1]|Out-Null;throw};&$adopt $r[0] $r[1]|Out-Null}
   $envFile=&$PrivateEnvFileFactory 'POSTGRES_PASSWORD' $password;if($null-eq$envFile-or$envFile.Verified-ne$true-or[string]::IsNullOrWhiteSpace($envFile.Path)){throw 'MAPLE_DBFIXTURE_REFUSED: private env-file lifecycle invalid.'}
   $create=@('create','--name',$plan.Container,'--label',$plan.OwnershipLabel,'--restart','no','--network',$plan.Network,'--network-alias','db','--publish',"127.0.0.1:$Port`:5432",'--volume',"$($plan.Volume):/var/lib/postgresql/data",'--env-file',$envFile.Path,'--health-cmd','pg_isready -U postgres -h 127.0.0.1 -p 5432','--health-interval','2s','--health-timeout','2s','--health-retries','15',$plan.ImageRef)
   try{&$checked $create 'container create'|Out-Null}catch{&$adopt 'container' $plan.Container|Out-Null;throw};&$adopt 'container' $plan.Container|Out-Null;&$envFile.Delete;$envFile=$null
   try{&$checked @('start',$recorded.container) 'container start'|Out-Null}catch{&$adopt 'container' $plan.Container|Out-Null;throw};&$adopt 'container' $recorded.container|Out-Null
   $deadline=(&$Clock).AddSeconds(90);while($true){$health=&$call @('inspect',$recorded.container,'--format','{{.State.Health.Status}}') 'health inspect';if($health.ExitCode-ne0){throw 'MAPLE_DBFIXTURE_FAILED: health state missing.'};$status=$health.Stdout.Trim();if($status-ceq'healthy'){break};if($status-ceq'unhealthy'){throw 'MAPLE_DBFIXTURE_FAILED: container unhealthy.'};if($status-cne'starting'){throw 'MAPLE_DBFIXTURE_FAILED: health state missing.'};if((&$Clock)-ge$deadline){throw 'MAPLE_DBFIXTURE_FAILED: 90 second health deadline exceeded.'};if((&$Wait 1000)-ne$true){throw 'MAPLE_DBFIXTURE_FAILED: health wait failed.'}}
   $execEnvFile=&$PrivateEnvFileFactory 'PGOPTIONS' "-cfarmrx.private_password=$password";if($null-eq$execEnvFile-or$execEnvFile.Verified-ne$true-or[string]::IsNullOrWhiteSpace($execEnvFile.Path)){throw 'MAPLE_DBFIXTURE_REFUSED: private exec env-file lifecycle invalid.'};try{Invoke-MapleDbFixtureInitialization $recorded.container $plan.Prefix $execEnvFile.Path $checked}finally{&$execEnvFile.Delete;$execEnvFile=$null}
   $proofSql="select contract_hash||'|'||result from api.fixture_proof where contract_hash='$($plan.Prefix)' order by contract_hash; select rolname||'|'||rolcanlogin from pg_roles where rolname in ('anon','authenticated','authenticator') order by rolname;";$proof=&$checked @('exec','-i',$recorded.container,'psql','-X','-At','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres','-f','-') 'fixture proof' $proofSql;$expected="$($plan.Prefix)|fixture-ready`nanon|f`nauthenticated|f`nauthenticator|t";if(($proof.Stdout.Trim()-replace"`r",'')-cne$expected){throw 'MAPLE_DBFIXTURE_FAILED: proof was not exact or contained extra rows.'};$result='MAPLE_SYNTHETIC_DB_FIXTURE_SMOKE_PASS'
  }catch{$primary=$_.Exception}
 }finally{
  if($null-ne$envFile){try{&$envFile.Delete}catch{$cleanupErrors.Add($_.Exception)}}
  if($null-ne$execEnvFile){try{&$execEnvFile.Delete}catch{$cleanupErrors.Add($_.Exception)}}
  foreach($r in @(@('container',$plan.Container),@('volume',$plan.Volume),@('network',$plan.Network))){try{$target=if($null-ne$recorded[$r[0]]){$recorded[$r[0]]}else{$r[1]};$actual=&$inspect $r[0] $target;if($null-eq$actual){continue};$rid=&$identity $r[0] $actual;if($null-eq$recorded[$r[0]]-or$rid-cne$recorded[$r[0]]-or(&$owner $r[0] $actual)-cne$plan.Token){throw "MAPLE_DBFIXTURE_REFUSED: $($r[0]) cleanup identity/ownership mismatch; retained."};if($r[0]-ceq'container'){if([bool]$actual.State.Running){&$checked @('stop','--time','60',$recorded.container) 'cleanup stop'|Out-Null;$stopped=&$inspect 'container' $recorded.container;if($null-eq$stopped-or(&$identity 'container' $stopped)-cne$recorded.container-or(&$owner 'container' $stopped)-cne$plan.Token-or[bool]$stopped.State.Running){throw 'MAPLE_DBFIXTURE_REFUSED: stopped container identity changed; retained.'}};&$checked @('rm',$recorded.container) 'container cleanup'|Out-Null}elseif($r[0]-ceq'network'){&$checked @('network','rm',$recorded.network) 'network cleanup'|Out-Null}else{&$checked @('volume','rm',$recorded.volume) 'volume cleanup'|Out-Null}}catch{$cleanupErrors.Add($_.Exception)}}
 }
 if($null-ne$primary-and$cleanupErrors.Count){$all=[Exception[]](@($primary)+@($cleanupErrors));throw [AggregateException]::new('MAPLE_DBFIXTURE_PRIMARY_AND_CLEANUP_FAILED',$all)};if($null-ne$primary){throw $primary};if($cleanupErrors.Count){throw [AggregateException]::new('MAPLE_DBFIXTURE_CLEANUP_FAILED',[Exception[]]@($cleanupErrors))};$result
}
if($MyInvocation.InvocationName-ne'.'){$plan=New-MapleSyntheticDbFixturePlan $SyntheticId $DbPort;if($Execute-and(-not$UnsafeReviewed-or-not$script:MapleDbFixtureExecutionUnlocked)){throw 'MAPLE_DBFIXTURE_REFUSED: execution remains internally locked pending Sol review.'};$plan|ConvertTo-Json -Depth 6}
