import { useEffect, useMemo, useState, type FormEvent } from 'react'
import type { Field, FieldsData, FieldsRepository } from './data/fields'
import { fieldLogMaximumObservedOn, validateFieldLogDraft, type FieldLogEntry, type FieldLogEntryDraft, type FieldLogRepository } from './data/fieldLog'
import { growingDegreeDays, weatherService } from './data/weatherService'
import { farmerError } from './lib/farmerErrors'

const today = () => new Date().toISOString().slice(0, 10)
const editable = (role: string) => role === 'owner' || role === 'manager' || role === 'worker'
const inches = new Intl.NumberFormat(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })

export function FieldLogPage({ fieldLogRepository, fieldsRepository }: { fieldLogRepository: FieldLogRepository; fieldsRepository: FieldsRepository }) {
  const [fieldsData, setFieldsData] = useState<FieldsData | null>(null); const [entries, setEntries] = useState<FieldLogEntry[]>([]); const [role, setRole] = useState<string>('read_only'); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true)
  const reload = async () => { setLoading(true); try { const [fields, log] = await Promise.all([fieldsRepository.getData(), fieldLogRepository.getData()]); setFieldsData(fields); setEntries(log.entries); setRole(log.viewer.role); setError(null) } catch (caught) { setError(farmerError(caught, 'open the field log')) } finally { setLoading(false) } }
  useEffect(() => { void reload() }, [])
  if (loading && !fieldsData) return <section className="page field-log-page"><p className="loading-state">Loading field log…</p></section>
  if (!fieldsData) return <section className="page field-log-page"><h1>Field Log</h1><p className="form-error">{error ?? 'Farm Rx could not load the field log.'}</p><button className="secondary-action" onClick={() => void reload()}>Try again</button></section>
  const activeFields = fieldsData.fields.filter((field) => field.is_active)
  return <section className="page field-log-page"><header className="page-heading"><div><h1>Field Log</h1><p>Rainfall and field notes, kept with each field.</p></div></header>{error && <p className="form-error">{error}</p>}{!activeFields.length ? <section className="empty-state"><h2>Add your first field to start a field log.</h2><p>Rainfall and notes stay tied to the field where they happened.</p></section> : <div className="field-log-list">{activeFields.map((field) => <FieldCard key={field.id} field={field} entries={entries.filter((entry) => entry.field_id === field.id)} assignments={fieldsData.crop_assignments} canEdit={editable(role)} repository={fieldLogRepository} refresh={reload} />)}</div>}</section>
}

function FieldCard({ field, entries, assignments, canEdit, repository, refresh }: { field: Field; entries: FieldLogEntry[]; assignments: FieldsData['crop_assignments']; canEdit: boolean; repository: FieldLogRepository; refresh: () => Promise<void> }) {
  const [mode, setMode] = useState<'rainfall' | 'note' | null>(null); const [editing, setEditing] = useState<FieldLogEntry | null>(null); const [pendingEntries, setPendingEntries] = useState<FieldLogEntry[]>([]); const [error, setError] = useState<string | null>(null); const year = new Date().getFullYear(); const timelineEntries = [...entries, ...pendingEntries.filter((pending) => !entries.some((entry) => entry.id === pending.id))].sort((a, b) => b.observed_on.localeCompare(a.observed_on)); const season = timelineEntries.filter((entry) => entry.entry_type === 'rainfall' && entry.observed_on >= `${year}-01-01` && entry.observed_on <= today()).reduce((sum, entry) => sum + (entry.rainfall_in ?? 0), 0)
  const plantingDate = useMemo(() => assignments.filter((assignment) => assignment.field_id === field.id && assignment.crop_year === year && !!assignment.planting_date).map((assignment) => assignment.planting_date!).sort()[0] ?? null, [assignments, field.id, year])
  async function save(draft: FieldLogEntryDraft) { try { const saved = await repository.saveEntry(draft); setMode(null); setEditing(null); setError(null); if (saved.pending) { setPendingEntries((current) => current.some((entry) => entry.id === saved.id) ? current.map((entry) => entry.id === saved.id ? saved : entry) : [...current, saved]); return } await refresh() } catch (caught) { setError(farmerError(caught, 'save this field log entry')) } }
  async function remove(entry: FieldLogEntry) { if (!window.confirm('Delete this field log entry?')) return; try { await repository.deleteEntry(entry.id); await refresh() } catch (caught) { setError(farmerError(caught, 'delete this field log entry')) } }
  return <article className="field-log-card"><header className="field-log-card-head"><div><h2>{field.name}</h2><p>{field.total_acres.toLocaleString()} acres</p></div><div className="rain-total"><span>{year} season</span><strong>{inches.format(season)} in</strong></div></header><Gdd field={field} plantingDate={plantingDate} />{canEdit && <div className="field-log-actions"><button className="primary-action" onClick={() => { setMode('rainfall'); setEditing(null) }}>Add rain</button><button className="secondary-action" onClick={() => { setMode('note'); setEditing(null) }}>Add note</button></div>}{(mode || editing) && <EntryForm entry={editing} type={editing?.entry_type ?? mode!} fieldId={field.id} save={save} cancel={() => { setMode(null); setEditing(null); setError(null) }} />}{error && <p className="form-error">{error}</p>}<section className="field-log-timeline"><h3>Timeline</h3>{timelineEntries.length ? timelineEntries.map((entry) => <div className="field-log-row" key={entry.id}><div><strong>{entry.observed_on}</strong><span>{entry.entry_type === 'rainfall' ? `${inches.format(entry.rainfall_in ?? 0)} in${entry.note ? ` · ${entry.note}` : ''}` : entry.note}</span>{entry.pending && <em className="field-log-pending">Pending sync</em>}</div>{canEdit && !entry.pending && <div className="field-log-row-actions"><button onClick={() => { setEditing(entry); setMode(null) }}>Edit</button><button className="danger-action" onClick={() => void remove(entry)}>Delete</button></div>}</div>) : <p className="card-empty">No rain or notes recorded yet.</p>}</section></article>
}

function EntryForm({ entry, type, fieldId, save, cancel }: { entry: FieldLogEntry | null; type: 'rainfall' | 'note'; fieldId: string; save: (draft: FieldLogEntryDraft) => Promise<void>; cancel: () => void }) {
  const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState<string | null>(null)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const rainfall = String(form.get('rainfall') ?? '').trim(); const note = String(form.get('note') ?? '').trim(); const draft: FieldLogEntryDraft = { id: entry?.id, field_id: fieldId, entry_type: type, observed_on: String(form.get('date')), rainfall_in: type === 'rainfall' ? rainfall === '' ? null : Number(rainfall) : null, note: note || null }; const validation = validateFieldLogDraft(draft); if (validation) { setMessage(validation); return } setSubmitting(true); setMessage(null); try { await save(draft) } finally { setSubmitting(false) } }
  return <form className="field-log-form" onSubmit={submit}><h3>{entry ? 'Edit' : type === 'rainfall' ? 'Add rain' : 'Add note'}</h3><label>Date<input name="date" type="date" max={fieldLogMaximumObservedOn()} defaultValue={entry?.observed_on ?? today()} required /></label>{type === 'rainfall' && <label>Rainfall (inches)<input name="rainfall" type="number" min="0" max="100" step="0.01" defaultValue={entry?.rainfall_in ?? ''} required /></label>}<label className={type === 'rainfall' ? 'wide' : ''}>{type === 'rainfall' ? 'Optional note' : 'Note'}<textarea name="note" maxLength={500} defaultValue={entry?.note ?? ''} required={type === 'note'} /></label>{message && <p className="form-error">{message}</p>}<div><button className="primary-action" disabled={submitting}>{submitting ? 'Saving…' : 'Save entry'}</button><button type="button" className="secondary-action" onClick={cancel}>Cancel</button></div></form>
}

function Gdd({ field, plantingDate }: { field: Field; plantingDate: string | null }) {
  const [state, setState] = useState<{ value: number | null; stale: boolean; error: boolean; through: string | null }>({ value: null, stale: false, error: false, through: null })
  useEffect(() => { let active = true; if (field.latitude === null || field.longitude === null || !plantingDate || !weatherService) { setState({ value: null, stale: false, error: false, through: null }); return () => { active = false } } void weatherService.fetchDailyHistory(field.latitude, field.longitude, plantingDate, today()).then((history) => { if (active) setState({ value: growingDegreeDays(history.daily), stale: history.stale, error: false, through: history.daily.at(-1)?.date ?? null }) }).catch(() => { if (active) setState({ value: null, stale: false, error: true, through: null }) }); return () => { active = false } }, [field.id, field.latitude, field.longitude, plantingDate])
  if (field.latitude === null || field.longitude === null || !plantingDate) return <p className="gdd-prompt">Add a location and planting date to see growing degree days.</p>
  if (plantingDate > today()) return <p className="gdd-prompt">Growing degree days will appear once this season has enough weather history.</p>
  if (state.error) return <p className="gdd-prompt">Growing degree days will appear once this season has enough weather history.</p>
  if (state.value === null) return <p className="gdd-prompt">Loading growing degree days…</p>
  return <p className="gdd-line"><strong>GDD since planting: {state.value.toLocaleString()}</strong><small>{state.stale ? 'Saved weather data — reconnect for the latest.' : state.through && state.through < today() ? `Weather data through ${state.through}.` : 'Based on daily high and low temperatures.'}</small></p>
}
