import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import type { CropAssignment, Field, FieldsData } from './data/fields'
import { canEditHarvest, harvestMaximumDate, harvestRevenue, validateHarvestDraft, yieldDelta, yieldPerAcre, type HarvestDraft, type HarvestRepository } from './data/harvest'
import { farmerError } from './lib/farmerErrors'
import { farmLocalCalendarDate } from './data/farmDates'
import { createSubmitLock } from './lib/submitLock'

const today = () => farmLocalCalendarDate()
const number = new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 })
const money = new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 2 })
const price = new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', minimumFractionDigits: 2, maximumFractionDigits: 2 })

export function HarvestPage({ harvestRepository }: { harvestRepository: HarvestRepository }) {
  const [data, setData] = useState<Awaited<ReturnType<HarvestRepository['getData']>> | null>(null)
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const reload = async () => { setLoading(true); try { const next = await harvestRepository.getData(); setData(next); setError(null) } catch (caught) { setError(farmerError(caught, 'open harvest records')) } finally { setLoading(false) } }
  useEffect(() => { void reload() }, [])
  const years = useMemo(() => data ? [...new Set(data.fieldsData.crop_assignments.map((item) => item.crop_year))].sort((a, b) => b - a) : [], [data])
  useEffect(() => { if (years.length && !years.includes(selectedYear)) setSelectedYear(years[0]) }, [selectedYear, years])
  if (loading && !data) return <section className="page harvest-page"><p className="loading-state">Loading harvest records…</p></section>
  if (!data) return <section className="page harvest-page"><h1>Harvest</h1><p className="form-error">{error ?? 'Farm Rx could not load harvest records.'}</p><button className="secondary-action" onClick={() => void reload()}>Try again</button></section>
  const fields = data.fieldsData.fields.filter((field) => field.is_active)
  const applySaved = (saved: { crop_assignment_id: string; harvested_bushels: number | null; harvest_date: string | null; actual_price_per_bu: number | null }) => setData((current) => current ? { ...current, fieldsData: { ...current.fieldsData, crop_assignments: current.fieldsData.crop_assignments.map((assignment) => assignment.id === saved.crop_assignment_id ? { ...assignment, harvested_bushels: saved.harvested_bushels, harvest_date: saved.harvest_date, actual_price_per_bu: saved.actual_price_per_bu } : assignment) } } : current)
  return <section className="page harvest-page"><header className="page-heading harvest-heading"><div><h1>Harvest</h1><p>Record actual bushels and keep your yield history in one place.</p></div><label className="harvest-year">Crop year<select value={selectedYear} onChange={(event) => setSelectedYear(Number(event.target.value))}>{years.length ? years.map((year) => <option key={year} value={year}>{year}</option>) : <option value={selectedYear}>{selectedYear}</option>}</select></label></header>{error && <p className="form-error">{error}</p>}{!fields.length ? <section className="empty-state"><h2>Add your first field to start harvest tracking.</h2><p>Harvest records stay with the field and crop that produced them.</p></section> : <div className="harvest-list">{fields.map((field) => <HarvestFieldCard key={field.id} field={field} fieldsData={data.fieldsData} selectedYear={selectedYear} canEdit={canEditHarvest(data.viewer.role)} repository={harvestRepository} onSaved={async (saved) => { applySaved(saved); if (!saved.pending) await reload() }} onError={setError} />)}</div>}</section>
}

function HarvestFieldCard({ field, fieldsData, selectedYear, canEdit, repository, onSaved, onError }: { field: Field; fieldsData: FieldsData; selectedYear: number; canEdit: boolean; repository: HarvestRepository; onSaved: (saved: Awaited<ReturnType<HarvestRepository['saveHarvest']>>) => Promise<void>; onError: (error: string | null) => void }) {
  const [editing, setEditing] = useState<CropAssignment | null>(null)
  const commodities = new Map(fieldsData.commodities.map((item) => [item.id, item.name]))
  const crops = fieldsData.crop_assignments.filter((item) => item.field_id === field.id && item.crop_year === selectedYear).sort((a, b) => a.planting_sequence - b.planting_sequence)
  const history = fieldsData.crop_assignments.filter((item) => item.field_id === field.id && item.crop_year < selectedYear && item.harvested_bushels !== null).sort((a, b) => b.crop_year - a.crop_year)
  return <article className="harvest-card"><header className="harvest-card-head"><div><h2>{field.name}</h2><p>{number.format(field.total_acres)} ac</p></div><span>{selectedYear} crops</span></header>{crops.length ? <div className="harvest-crops">{crops.map((crop) => <section className="harvest-crop" key={crop.id}><div className="harvest-crop-main"><h3>{commodities.get(crop.commodity_id) ?? 'Crop'}</h3><p>{number.format(crop.planted_acres)} ac planted{crop.expected_yield_per_acre === null ? '' : ` · ${number.format(crop.expected_yield_per_acre)} bu/ac expected`}</p><HarvestResults crop={crop} /></div>{canEdit && <button className="secondary-action harvest-enter" type="button" onClick={() => { setEditing(editing?.id === crop.id ? null : crop); onError(null) }}>{editing?.id === crop.id ? 'Close' : crop.harvested_bushels === null ? 'Enter harvest' : 'Edit harvest'}</button>}{editing?.id === crop.id && <HarvestForm crop={crop} save={async (draft) => { try { const saved = await repository.saveHarvest(draft); setEditing(null); onError(null); await onSaved(saved) } catch (caught) { onError(farmerError(caught, 'save this harvest entry')) } }} cancel={() => setEditing(null)} />}</section>)}</div> : <p className="card-empty">No crops are assigned to this field for {selectedYear}.</p>}<section className="yield-history"><h3>Yield history</h3>{history.length ? <div className="yield-history-strip">{history.map((crop) => { const actual = yieldPerAcre(crop.harvested_bushels, crop.planted_acres); return <span key={crop.id}><strong>{crop.crop_year} · {commodities.get(crop.commodity_id) ?? 'Crop'}</strong><em>{actual === null ? '—' : `${number.format(actual)} bu/ac`}</em></span> })}</div> : <p className="card-empty">No prior harvested yields recorded for this field.</p>}</section></article>
}

function HarvestResults({ crop }: { crop: CropAssignment }) {
  const actual = yieldPerAcre(crop.harvested_bushels, crop.planted_acres)
  if (actual === null) return null
  const delta = yieldDelta(actual, crop.expected_yield_per_acre)
  const revenue = harvestRevenue(crop.harvested_bushels, crop.actual_price_per_bu, crop.expected_price_per_bu)
  return <div className="harvest-results"><span><small>Actual yield/ac</small><strong>{number.format(actual)} bu/ac</strong></span><span className={delta === null ? '' : delta >= 0 ? 'over-plan' : 'under-plan'}><small>Against plan</small><strong>{delta === null ? 'No expected yield set' : delta >= 0 ? `+${number.format(delta)} bu/ac over plan` : `${number.format(Math.abs(delta))} bu/ac under plan`}</strong></span><span><small>Actual revenue</small><strong>{revenue === null ? 'No price entered' : `${money.format(revenue.value)} (${revenue.priceSource} price)`}</strong></span></div>
}

function HarvestForm({ crop, save, cancel }: { crop: CropAssignment; save: (draft: HarvestDraft) => Promise<void>; cancel: () => void }) {
  const submitLock = useRef(createSubmitLock()); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState<string | null>(null)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!submitLock.current.acquire()) return; try { const form = new FormData(event.currentTarget); const bushels = String(form.get('bushels') ?? '').trim(); const harvestDate = String(form.get('harvestDate') ?? '').trim(); const actualPrice = String(form.get('actualPrice') ?? '').trim(); const draft: HarvestDraft = { crop_assignment_id: crop.id, harvested_bushels: bushels === '' ? null : Number(bushels), harvest_date: harvestDate || null, actual_price_per_bu: actualPrice === '' ? null : Number(actualPrice) }; const validation = validateHarvestDraft(draft); if (validation) { setMessage(validation); return } if (draft.harvest_date && crop.planting_date && draft.harvest_date < crop.planting_date) { setMessage('Harvest date cannot be before the planting date.'); return } setSubmitting(true); setMessage(null); await save(draft) } finally { setSubmitting(false); submitLock.current.release() } }
  return <form className="harvest-form" onSubmit={submit}><h3>Enter harvest</h3><label>Harvested bushels<input name="bushels" type="number" min="0" step="0.01" inputMode="decimal" defaultValue={crop.harvested_bushels ?? ''} autoFocus /></label><label>Harvest date<input name="harvestDate" type="date" min={crop.planting_date ?? undefined} max={harvestMaximumDate()} defaultValue={crop.harvest_date ?? today()} /></label><label>Actual price per bu <span>(optional)</span><input name="actualPrice" type="number" min="0" step="0.000001" inputMode="decimal" defaultValue={crop.actual_price_per_bu ?? ''} placeholder={crop.expected_price_per_bu === null ? 'No expected price' : `Expected ${price.format(crop.expected_price_per_bu)}`} /></label>{message && <p className="form-error">{message}</p>}<div><button className="primary-action" disabled={submitting}>{submitting ? 'Saving…' : 'Save harvest'}</button><button className="secondary-action" type="button" onClick={cancel}>Cancel</button></div></form>
}
