import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import type { Field, FieldsRepository } from './data/fields'
import { SCOUTING_OFFLINE_DELETE_MESSAGE, scoutingMaximumObservedOn, validateScoutingNoteDraft, type ScoutingNote, type ScoutingNoteDraft, type ScoutingRepository } from './data/scouting'
import { signedUrl, validateScoutingPhotoFile } from './data/scoutingStorage'
import { normalizeScoutingCoordinate } from './data/scouting'
import { farmerError } from './lib/farmerErrors'
import { farmLocalCalendarDate } from './data/farmDates'
import { notificationsRepository } from './data'
import { useAuth } from './auth/AuthProvider'
import { createSubmitLock, createSubmitLockMap } from './lib/submitLock'

const today = () => farmLocalCalendarDate()
const categories = ['weed', 'disease', 'insect', 'other'] as const
const categoryLabel = (category: string) => category[0].toUpperCase() + category.slice(1)

export function ScoutingPage({ scoutingRepository, fieldsRepository }: { scoutingRepository: ScoutingRepository; fieldsRepository: FieldsRepository }) {
  const { user } = useAuth()
  const [fields, setFields] = useState<Field[]>([]); const [notes, setNotes] = useState<ScoutingNote[]>([]); const [role, setRole] = useState('read_only'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const reload = async () => { setLoading(true); try { const [fieldData, scouting] = await Promise.all([fieldsRepository.getData(), scoutingRepository.getData()]); setFields(fieldData.fields.filter((field) => field.is_active)); setNotes(scouting.notes); setRole(scouting.viewer.role); setError(null) } catch (caught) { setError(farmerError(caught, 'open scouting notes')) } finally { setLoading(false) } }
  useEffect(() => { void reload() }, [])
  if (loading) return <section className="page scouting-page"><p className="loading-state">Loading scouting notes…</p></section>
  if (error && !fields.length) return <section className="page scouting-page"><h1>Scouting</h1><p className="form-error">{error}</p><button className="secondary-action" onClick={() => void reload()}>Try again</button></section>
  return <section className="page scouting-page"><header className="page-heading"><div><h1>Scouting</h1><p>Field observations and photos, kept where you need them.</p></div></header>{error && <p className="form-error">{error}</p>}{!fields.length ? <section className="empty-state"><h2>Add your first field to start scouting.</h2><p>Scouting notes stay tied to the field where you found them.</p></section> : <div className="scouting-list">{fields.map((field) => <ScoutingFieldCard key={field.id} field={field} farmId={field.farm_id} notes={notes.filter((note) => note.field_id === field.id)} canEdit={role === 'owner' || role === 'manager' || role === 'worker'} repository={scoutingRepository} refresh={reload} recipientId={user?.id ?? null} />)}</div>}</section>
}

function ScoutingFieldCard({ field, farmId, notes, canEdit, repository, refresh, recipientId }: { field: Field; farmId: string; notes: ScoutingNote[]; canEdit: boolean; repository: ScoutingRepository; refresh: () => Promise<void>; recipientId: string | null }) {
  const deleteLocks = useRef(createSubmitLockMap()); const [editing, setEditing] = useState<ScoutingNote | null>(null); const [adding, setAdding] = useState(false); const [pending, setPending] = useState<ScoutingNote[]>([]); const [deletedIds, setDeletedIds] = useState<Set<string>>(() => new Set()); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [lightbox, setLightbox] = useState<string | null>(null)
  const timeline = [...notes, ...pending.filter((candidate) => !notes.some((note) => note.id === candidate.id))].filter((note) => !deletedIds.has(note.id)).sort((a, b) => b.observed_on.localeCompare(a.observed_on) || b.created_at.localeCompare(a.created_at))
  async function save(draft: ScoutingNoteDraft, files: File[]) { try { let offlinePhotoMessage: string | null = null; let filesToSave = files; if (files.length && navigator.onLine === false) { if (!draft.note.trim()) throw new Error('Photos need a connection. Add a note first, then add photos when you are back online.'); offlinePhotoMessage = 'Photos need a connection — your note text is waiting to sync. Add photos when you are back online.'; filesToSave = [] }
    const saved = await repository.saveNote(draft, filesToSave); if (draft.create_task && recipientId) void notificationsRepository.raiseNotification(farmId, recipientId, 'scouting', `Follow up on ${field.name}`, 'A scouting follow-up task was added.', '/scouting', `scouting:${saved.id}`).catch(() => undefined); setAdding(false); setEditing(null); setError(offlinePhotoMessage); if (saved.pending) { setPending((current) => current.some((note) => note.id === saved.id) ? current.map((note) => note.id === saved.id ? saved : note) : [...current, saved]); return } await refresh()
  } catch (caught) { setError(farmerError(caught, 'save this scouting note')) } }
  async function remove(note: ScoutingNote) { const deleteLock = deleteLocks.current.get(note.id); if (!window.confirm('Delete this scouting note and its photos?') || !deleteLock.acquire()) return; try { const receipt = await repository.deleteNote(note.id, note.photos.map((photo) => photo.storage_path)); setPending((current) => current.filter((item) => item.id !== note.id)); setDeletedIds((current) => new Set(current).add(note.id)); setError(null); if (receipt.pending) { setNotice(SCOUTING_OFFLINE_DELETE_MESSAGE); return } setNotice(null); await refresh() } catch (caught) { setError(farmerError(caught, 'delete this scouting note')) } finally { deleteLock.release() } }
  return <article className="scouting-card"><header className="scouting-card-head"><div><h2>{field.name}</h2><p>{field.total_acres.toLocaleString()} acres</p></div>{canEdit && <button className="primary-action" onClick={() => { setAdding(true); setEditing(null); setError(null) }}>New scouting note</button>}</header>{(adding || editing) && <ScoutingForm key={editing?.id ?? 'new'} field={field} entry={editing} onSave={save} onCancel={() => { setAdding(false); setEditing(null); setError(null) }} />}{error && <p className="form-error scouting-error">{error}</p>}{notice && <p className="field-log-pending" role="status">{notice}</p>}<section className="scouting-timeline"><h3>Timeline</h3>{timeline.length ? timeline.map((note) => <ScoutingRow key={note.id} note={note} canEdit={canEdit} edit={() => { setEditing(note); setAdding(false); setError(null) }} remove={() => void remove(note)} showPhoto={setLightbox} />) : <p className="card-empty">No scouting notes recorded yet.</p>}</section>{lightbox && <div className="photo-lightbox" role="dialog" aria-modal="true" aria-label="Scouting photo"><button aria-label="Close photo" onClick={() => setLightbox(null)}>Close</button><img src={lightbox} alt="Enlarged scouting observation" /></div>}</article>
}

function ScoutingForm({ field, entry, onSave, onCancel }: { field: Field; entry: ScoutingNote | null; onSave: (draft: ScoutingNoteDraft, files: File[]) => Promise<void>; onCancel: () => void }) {
  const submitLock = useRef(createSubmitLock()); const [category, setCategory] = useState<ScoutingNote['category']>(entry?.category ?? 'weed'); const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(entry?.latitude === null || entry?.latitude === undefined ? null : { latitude: entry.latitude, longitude: entry.longitude! }); const [files, setFiles] = useState<File[]>([]); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState<string | null>(null)
  const previews = useMemo(() => files.map((file) => ({ file, url: URL.createObjectURL(file) })), [files]); useEffect(() => () => previews.forEach((preview) => URL.revokeObjectURL(preview.url)), [previews])
  function useLocation() { if (!navigator.geolocation) { setMessage('Location is not available in this browser.'); return } setMessage('Getting your current location…'); navigator.geolocation.getCurrentPosition((position) => { setLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude }); setMessage('Location added.') }, () => setMessage('We could not use your location. You can save without it.'), { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 }) }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!submitLock.current.acquire()) return; try { const form = new FormData(event.currentTarget); const id = entry?.id ?? crypto.randomUUID(); const badFile = files.map(validateScoutingPhotoFile).find((message) => message !== null); if (badFile) { setMessage(badFile); return } const draft: ScoutingNoteDraft = { id, field_id: field.id, observed_on: String(form.get('date') ?? ''), category, note: String(form.get('note') ?? '').trim(), latitude: normalizeScoutingCoordinate(location?.latitude ?? null), longitude: normalizeScoutingCoordinate(location?.longitude ?? null), photos: entry?.photos.map((photo) => ({ id: photo.id, storage_path: photo.storage_path })) ?? [], create_task: form.get('create_task') === 'on' }; const validation = validateScoutingNoteDraft({ ...draft, photos: [...draft.photos, ...files.map((file) => ({ storage_path: `${field.farm_id}/${field.id}/${id}/${file.name}` }))] }); if (validation) { setMessage(validation); return } setSubmitting(true); setMessage(null); await onSave(draft, files) } finally { setSubmitting(false); submitLock.current.release() } }
  return <form className="scouting-form" onSubmit={submit}><h3>{entry ? 'Edit scouting note' : 'New scouting note'}</h3><label>Date<input name="date" type="date" defaultValue={entry?.observed_on ?? today()} max={scoutingMaximumObservedOn()} required /></label><fieldset><legend>Category</legend><div className="category-chips">{categories.map((item) => <button type="button" className={category === item ? 'active' : ''} onClick={() => setCategory(item)} key={item}>{categoryLabel(item)}</button>)}</div></fieldset><label className="scouting-wide">What did you find?<textarea name="note" maxLength={2000} defaultValue={entry?.note ?? ''} placeholder="Example: Waterhemp along the west edge" /></label><div className="location-line"><button type="button" className="secondary-action" onClick={useLocation}>Use my location</button>{location && <span>{location.latitude.toFixed(6)}, {location.longitude.toFixed(6)}</span>}</div><label className="scouting-wide">Photos<input type="file" accept="image/*" capture="environment" multiple onChange={(event) => setFiles(Array.from(event.currentTarget.files ?? []))} /><small>Photos need a connection to upload.</small></label>{previews.length > 0 && <div className="photo-preview">{previews.map(({ file, url }) => <img key={`${file.name}-${file.lastModified}`} src={url} alt={`Selected ${file.name}`} />)}</div>}<label className="task-check scouting-wide"><input type="checkbox" name="create_task" defaultChecked={false} /> Add a follow-up task</label>{message && <p className="form-error scouting-wide">{message}</p>}<div className="scouting-wide"><button className="primary-action" disabled={submitting}>{submitting ? 'Saving…' : 'Save scouting note'}</button><button className="secondary-action" type="button" onClick={onCancel} disabled={submitting}>Cancel</button></div></form>
}

function ScoutingRow({ note, canEdit, edit, remove, showPhoto }: { note: ScoutingNote; canEdit: boolean; edit: () => void; remove: () => void; showPhoto: (url: string) => void }) { const [urls, setUrls] = useState<Record<string, string>>({}); useEffect(() => { let active = true; void Promise.all(note.photos.map(async (photo) => [photo.id, await signedUrl(photo.storage_path)] as const)).then((next) => { if (active) setUrls(Object.fromEntries(next)) }).catch(() => { if (active) setUrls({}) }); return () => { active = false } }, [note.id, note.photos])
  return <div className="scouting-row"><div className="scouting-row-main"><div className="scouting-row-meta"><span className={`category-chip ${note.category}`}>{categoryLabel(note.category)}</span><strong>{note.observed_on}</strong>{note.latitude !== null && <span>{note.latitude.toFixed(5)}, {note.longitude!.toFixed(5)}</span>}</div>{note.note && <p>{note.note}</p>}{note.photos.length > 0 && <div className="scouting-photos">{note.photos.map((photo) => urls[photo.id] ? <button key={photo.id} onClick={() => showPhoto(urls[photo.id])}><img src={urls[photo.id]} alt={`${categoryLabel(note.category)} observation`} /></button> : <span className="photo-loading" key={photo.id}>Loading photo…</span>)}</div>}{note.pending && <em className="field-log-pending">Pending sync</em>}</div>{canEdit && !note.pending && <div className="field-log-row-actions"><button onClick={edit}>Edit</button><button className="danger-action" onClick={remove}>Delete</button></div>}</div> }
