import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { fieldLocationClient, fieldsRepository, notificationsRepository } from './data'
import { useAuth } from './auth/AuthProvider'
import type { Field } from './data/fields'
import { bestWindowToday, compassLabel, evaluateSprayWindow, formatF, formatHour, formatMph, weatherService } from './data/weatherService'
import type { DailyForecast, ForecastBundle, WeatherSample } from './data/weather'
import { farmerError } from './lib/farmerErrors'
import { createSubmitLock } from './lib/submitLock'

type CardState = { loading: boolean; bundle: ForecastBundle | null; error: string | null }
const initial: CardState = { loading: false, bundle: null, error: null }
const dailyFor = (bundle: ForecastBundle, time: string): DailyForecast | undefined => bundle.daily.find((day) => day.date === time.slice(0, 10)) ?? bundle.daily[0]
const contextFor = (bundle: ForecastBundle, sample: WeatherSample) => { const day = dailyFor(bundle, sample.time); return { now: bundle.current.time, hourly: bundle.hourly, sunrise: day?.sunrise ?? null, sunset: day?.sunset ?? null } }
const displayTime = (value: string) => new Intl.DateTimeFormat(undefined, { weekday: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date(value))

export function WeatherPage() {
  const { user } = useAuth()
  const locationLocks = useRef(new Map<string, ReturnType<typeof createSubmitLock>>()); const [fields, setFields] = useState<Field[]>([]); const [cards, setCards] = useState<Record<string, CardState>>({}); const [loading, setLoading] = useState(true); const [pageError, setPageError] = useState<string | null>(null); const [manualFor, setManualFor] = useState<string | null>(null); const [message, setMessage] = useState<Record<string, string>>({})
  const located = useMemo(() => fields.filter((field) => field.latitude !== null && field.longitude !== null), [fields])
  const loadFields = async () => { setLoading(true); setPageError(null); try { setFields((await fieldsRepository.getData()).fields.filter((field) => field.is_active)) } catch (error) { setPageError(farmerError(error, 'load your fields')) } finally { setLoading(false) } }
  const refreshField = async (field: Field) => { if (field.latitude === null || field.longitude === null || !weatherService) return; setCards((old) => ({ ...old, [field.id]: { ...(old[field.id] ?? initial), loading: true, error: null } })); try { const bundle = await weatherService.fetchForecast(field.latitude, field.longitude); setCards((old) => ({ ...old, [field.id]: { loading: false, bundle, error: null } })) } catch (error) { const message = error instanceof Error && error.message === 'Forecast unavailable — reconnect for the latest.' ? error.message : farmerError(error, 'load this forecast'); setCards((old) => ({ ...old, [field.id]: { loading: false, bundle: old[field.id]?.bundle ?? null, error: message } })) } }
  const refreshAll = async () => { await Promise.all(located.map(refreshField)) }
  useEffect(() => { void loadFields() }, [])
  useEffect(() => { if (located.length) void refreshAll() }, [located.length])
  const sprayLevels = useRef(new Map<string, string>())
  useEffect(() => {
    if (!user) return
    for (const field of located) {
      const bundle = cards[field.id]?.bundle
      if (!bundle) continue
      const verdict = evaluateSprayWindow(bundle.current, contextFor(bundle, bundle.current)).level
      const day = bundle.current.time.slice(0, 10); const key = `${field.id}:${day}`; const previous = sprayLevels.current.get(key)
      sprayLevels.current.set(key, verdict)
      if (previous && previous !== 'good' && verdict === 'good') {
        void notificationsRepository.raiseNotification(field.farm_id, user.id, 'spray', `Spray window is good on ${field.name}`, 'Current field conditions have turned good for spraying today.', '/weather', `spray:${field.id}:${day}`).catch(() => undefined)
      }
    }
  }, [cards, located, user])
  const saveLocation = async (field: Field, latitude: number, longitude: number, source: 'gps' | 'manual') => { const lock = locationLocks.current.get(field.id) ?? createSubmitLock(); locationLocks.current.set(field.id, lock); if (!lock.acquire()) return; try { setMessage((old) => ({ ...old, [field.id]: 'Saving location…' })); const saved = await fieldLocationClient.saveLocation(field.id, latitude, longitude, source); const next = { ...field, latitude, longitude, location_source: source }; setFields((rows) => rows.map((row) => row.id === field.id ? next : row)); setMessage((old) => ({ ...old, [field.id]: saved ? 'Location saved.' : 'Location saved on this device. Farm Rx will try when you reconnect; if you do not have permission, it will stay saved here and show needs attention.' })); setManualFor(null); void refreshField(next) } catch (error) { setMessage((old) => ({ ...old, [field.id]: farmerError(error, 'save this location') })) } finally { lock.release() } }
  const useLocation = (field: Field) => { if (!navigator.geolocation) { setManualFor(field.id); setMessage((old) => ({ ...old, [field.id]: 'Location is not available here. Enter it below instead.' })); return } setMessage((old) => ({ ...old, [field.id]: 'Getting your current location…' })); navigator.geolocation.getCurrentPosition((position) => { void saveLocation(field, position.coords.latitude, position.coords.longitude, 'gps') }, () => { setManualFor(field.id); setMessage((old) => ({ ...old, [field.id]: 'We could not use your location. Enter it below instead.' })) }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 }) }
  if (loading) return <main className="weather-page"><header className="page-heading"><div><p className="eyebrow">Field forecast</p><h1>Weather &amp; Spray</h1></div></header><section className="weather-card loading-state">Loading your fields…</section></main>
  return <main className="weather-page"><header className="page-heading weather-heading"><div><p className="eyebrow">Field forecast</p><h1>Weather &amp; Spray</h1><p>See field conditions before you head out.</p></div><button className="secondary-action" onClick={() => void refreshAll()} disabled={!located.length}>Refresh weather</button></header>{pageError && <p className="weather-error" role="alert">{pageError}</p>}<p className="weather-guidance">Spray guidance only — always follow the product label and your applicator judgment.</p>{!pageError && !fields.length && <section className="weather-card empty-weather"><h2>No active fields yet</h2><p>Add a field first, then set its location to see a forecast.</p></section>}{fields.map((field) => <WeatherCard key={field.id} field={field} state={cards[field.id] ?? initial} manual={manualFor === field.id} message={message[field.id]} onUseLocation={() => useLocation(field)} onShowManual={() => setManualFor(field.id)} onManual={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void saveLocation(field, Number(form.get('latitude')), Number(form.get('longitude')), 'manual') }} onRefresh={() => void refreshField(field)} />)}</main>
}
function WeatherCard({ field, state, manual, message, onUseLocation, onShowManual, onManual, onRefresh }: { field: Field; state: CardState; manual: boolean; message?: string; onUseLocation: () => void; onShowManual: () => void; onManual: (event: FormEvent<HTMLFormElement>) => void; onRefresh: () => void }) {
  if (field.latitude === null || field.longitude === null) return <section className="weather-card location-card"><h2>{field.name}</h2><p>Set location to see weather.</p><button className="primary-action" onClick={onUseLocation}>Use my current location</button><button className="text-action" onClick={onShowManual}>Enter latitude and longitude</button>{manual && <form className="weather-location-form" onSubmit={onManual}><label>Latitude<input name="latitude" type="number" step="0.000001" min="-90" max="90" required /></label><label>Longitude<input name="longitude" type="number" step="0.000001" min="-180" max="180" required /></label><button className="primary-action">Save location</button></form>}{message && <p className="weather-note" role="status">{message}</p>}</section>
  const bundle = state.bundle
  return <section className="weather-card"><div className="weather-card-title"><div><h2>{field.name}</h2><p>{field.latitude.toFixed(3)}, {field.longitude.toFixed(3)}</p></div><button className="secondary-action" onClick={onRefresh} disabled={state.loading}>{state.loading ? 'Refreshing…' : 'Refresh'}</button></div>{state.loading && !bundle && <p className="weather-note">Loading this forecast…</p>}{state.error && <p className="weather-error" role="alert">{state.error}</p>}{bundle && <ForecastView bundle={bundle} />}{message && <p className="weather-note" role="status">{message}</p>}</section>
}
function ForecastView({ bundle }: { bundle: ForecastBundle }) { const ctx = contextFor(bundle, bundle.current); const verdict = evaluateSprayWindow(bundle.current, ctx); const window = bestWindowToday(bundle.hourly, ctx); const hours = bundle.hourly.filter((hour) => Date.parse(hour.time) >= Date.parse(bundle.current.time)).slice(0, 12); return <><div className="weather-now"><div><strong>{formatF(bundle.current.temperature_f)}</strong><span>Now</span></div><div><strong>{formatMph(bundle.current.wind_speed_mph)} {compassLabel(bundle.current.wind_direction_degrees)}</strong><span>Wind · gusts {formatMph(bundle.current.wind_gusts_mph)}</span></div><div><strong>{bundle.current.relative_humidity}%</strong><span>Humidity · rain {bundle.current.precipitation_in.toFixed(2)} in</span></div></div><div className="spray-summary"><div className={`spray-light ${verdict.level}`}><strong>{verdict.level === 'good' ? 'Good' : verdict.level === 'caution' ? 'Caution' : 'Poor'}</strong><span>Spray now</span></div><div><h3>Can I spray right now?</h3><p>{verdict.reasons[0]}</p><strong className="best-window">{window?.label ?? 'No good window today'}</strong></div></div><div className="hour-strip" aria-label="Next 12 hours spray guidance">{hours.map((hour) => { const level = evaluateSprayWindow(hour, contextFor(bundle, hour)).level; return <div key={hour.time} className={level}><span>{formatHour(hour.time)}</span><b>{level === 'good' ? 'Good' : level === 'caution' ? 'Care' : 'Wait'}</b></div> })}</div><div className="daily-row">{bundle.daily.map((day) => <div key={day.date}><strong>{new Intl.DateTimeFormat(undefined, { weekday: 'short' }).format(new Date(`${day.date}T12:00:00`))}</strong><span>{formatF(day.temperature_max_f)} / {formatF(day.temperature_min_f)}</span><span>Rain {Math.round(day.precipitation_probability_max ?? 0)}%</span></div>)}</div><p className="weather-stamp">{bundle.stale ? 'Showing your last forecast — reconnect for the latest. ' : ''}As of {displayTime(bundle.fetched_at)}.</p></> }
